version: '3.9'

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass mysecretpassword --loglevel warning
    volumes:
      - ./.docker/redis:/data